version: "3"
services:
  api-gateway:
    build: "./api-gateway"
    depends_on:
      - accounts-service
      - users-service
    ports:
      - 7000:7000
    volumes:
      - ./api-gateway:/opt/app

  accounts-service:
    build: "./accounts-service"
    depends_on:
      - accounts-service-db
    environment:
      - DATABASE_URL=mysql://root:password@accounts-service-db/db
      - TYPEORM_URL=mysql://root:password@accounts-service-db/db
    ports:
      - 7100:7100
    volumes:
      - ./accounts-service:/opt/app

  accounts-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - 0.0.0.0:7200:3306

  users-service:
    build: "./users-service"
    depends_on:
      - users-service-db
    environment:
      - DATABASE_URL=mysql://root:password@users-service-db/db
      - TYPEORM_URL=mysql://root:password@users-service-db/db
    ports:
      - 7101:7101
    volumes:
      - ./users-service:/opt/app

  users-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - 0.0.0.0:7201:3306
